using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MoveObject : MonoBehaviour
{
    float speed = 4;
    float rotSpeed = 80;
    float rot = 0f;
    float gravity = 8;

    Vector3 moveDir = Vector3.zero;

    CharacterController controller;
    Animator anim;
    // Start is called before the first frame update
    void Start()
    {
        controller = GetComponent<CharacterController>();
        anim = GetComponent<Animator>();
    }

	// Update is called once per frame
	void Update()
	{
		if (controller.isGrounded)
		{
			if (Input.GetKey(KeyCode.W))
			{
				moveDir = new Vector3(0, 0, 1);
				moveDir *= speed;
				moveDir = transform.TransformDirection(moveDir);
				anim.SetInteger("condition", 1);
			}
			if (Input.GetKeyUp(KeyCode.W))
			{
				moveDir = new Vector3(0, 0, 0);
				anim.SetInteger("condition", 0);
			}
		}
		rot += Input.GetAxis("Horizontal") * rotSpeed * Time.deltaTime;
		transform.eulerAngles = new Vector3(0, rot, 0);

		moveDir.y -= gravity * Time.deltaTime;
		controller.Move(moveDir * Time.deltaTime);
	}
}
